name: "Bash Action Template"
author: "PhantasmicDev"
description: "A template with the bare minimum to begin developing a custom GitHub action that runs a bash script."
branding:
  icon: "file-text"
  color: "white"

inputs:
  target-branch:
    description: "The desired branch push the target directory to."
  directory:
    description: "The desired directory for the branch."

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
