name: "Branch from Directory"
author: "PhantasmicDev"
description: "Push a directory as a branch in your repository."
branding:
  icon: "git-branch"
  color: "green"

inputs:
  branch:
    description: "The desired branch push the target directory to."
    required: true
  directory:
    description: "The desired directory for the branch."
    required: true
  tag:
    description: "The tag for the release."
  checkout:
    description: "Checkout repository."
    default: "true"
  ref:
    description: "The branch to checkout if 'checkout' is set to true."
    default: ${{ github.ref }}

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_CHECKOUT: ${{ inputs.checkout }}
        INPUT_REF: ${{ inputs.ref }}

