name: "Branch from Directory"
author: "PhantasmicDev"
description: ""
branding:
  icon: "git-branch"
  color: "green"

inputs:
  branch:
    description: "The desired branch push the target directory to."
    required: true
  directory:
    description: "The desired directory for the branch."
    required: true
  tag:
    description: "The tag for the release."

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_TAG: ${{ inputs.tag }}
